[[fetch]]
files = [
    "./microlog/__init__.py",
    "./microlog/api.py",
    "./microlog/models.py",
    "./microlog/config.py",
    "./microlog/log.py",

    "./microlog/tracer.py",

    "./dashboard/__init__.py",
    "./dashboard/main.py",
    "./dashboard/canvas.py",
    "./dashboard/colors.py",
    "./dashboard/config.py",
    "./dashboard/dialog.py",
    "./dashboard/markdown.py",
    "./dashboard/profiler.py",
    "./dashboard/design.py",
    "./dashboard/tips.py",
    "./dashboard/treeview.py",
    "./dashboard/views/__init__.py",
    "./dashboard/views/call.py",
    "./dashboard/views/marker.py",
    "./dashboard/views/status.py",
    "./dashboard/views/timeline.py",
]