# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "micrologai"
version = "1.3.3"
description = "A continuous profiler and logger for Python written entirely in Python"
readme = "README.md"
authors = [{ name = "Chris Laffra", email = "chris@chrislaffra.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["profiler", "logging", "understanding", "performance", "cpu", "memory", "leaks"]
dependencies = [
    "appdata",
    "psutil",
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["openai", "mock", "pytest"]

[tool.setuptools.package-data]
mypkg = ["*.png", "*.html"]

[project.urls]
Homepage = "https://github.com/micrologai/microlog"

[project.scripts]
server = "microlog.server:main"
