name = "Microlog"

[files]
"ltk/jquery.py" = "ltk/jquery.py"
"ltk/widgets.py" = "ltk/widgets.py"
"ltk/pubsub.py" = "ltk/pubsub.py"
"ltk/logger.py" = "ltk/logger.py"
"ltk/__init__.py" = "ltk/__init__.py"
"ltk/ltk.js" = "ltk/ltk.js"
"ltk/ltk.css" = "ltk/ltk.css"

"microlog/__init__.py" = "./microlog/__init__.py"
"microlog/api.py" = "./microlog/api.py"
"microlog/models.py" = "./microlog/models.py"
"microlog/config.py" = "./microlog/config.py"
"microlog/tracer.py" = "./microlog/tracer.py"
"microlog/dashboard/__init__.py" = "./microlog/dashboard/__init__.py"
"microlog/dashboard/main.py" = "./microlog/dashboard/main.py"
"microlog/dashboard/ui.py" = "./microlog/dashboard/ui.py"
"microlog/dashboard/canvas.py" = "./microlog/dashboard/canvas.py"
"microlog/dashboard/colors.py" = "./microlog/dashboard/colors.py"
"microlog/dashboard/config.py" = "./microlog/dashboard/config.py"
"microlog/dashboard/dialog.py" = "./microlog/dashboard/dialog.py"
"microlog/dashboard/flamegraph.py" = "./microlog/dashboard/flamegraph.py"
"microlog/dashboard/markdown.py" = "./microlog/dashboard/markdown.py"
"microlog/dashboard/design.py" = "./microlog/dashboard/design.py"
"microlog/dashboard/treeview.py" = "./microlog/dashboard/treeview.py"
"microlog/dashboard/views/__init__.py" = "./microlog/dashboard/views/__init__.py"
"microlog/dashboard/views/call.py" = "./microlog/dashboard/views/call.py"
"microlog/dashboard/views/marker.py" = "./microlog/dashboard/views/marker.py"
"microlog/dashboard/views/status.py" = "./microlog/dashboard/views/status.py"
"microlog/dashboard/views/timeline.py" = "./microlog/dashboard/views/timeline.py"