#
# Microlog. Copyright (c) 2023 laffra, dcharbon. All rights reserved.
#

LINE_HEIGHT = 22
PIXELS_PER_SECOND = 100

FONT_SIZE_SMALL = 12
FONT_SIZE_REGULAR = 15
FONT_SIZE_LARGE = 20
FONT_NAME = "Arial"
FONT_SMALL = f"{FONT_SIZE_SMALL}px {FONT_NAME}"
FONT_REGULAR = f"{FONT_SIZE_REGULAR}px {FONT_NAME}"
FONT_LARGE = f"{FONT_SIZE_LARGE}px {FONT_NAME}"

STATS_OFFSET_Y = 0
STATS_HEIGHT = 140
TIMELINE_OFFSET_Y = STATS_OFFSET_Y + STATS_HEIGHT
TIMELINE_HEIGHT = 40
FLAME_OFFSET_Y = TIMELINE_OFFSET_Y + TIMELINE_HEIGHT + 2

BACKGROUND_COLOR = "#646363"

CALL_HOVER_DIALOG_DELAY = 500

SCALE_MAX = 4096
SCALE_MIN = 0.032

CANVAS_INITIAL_OFFSET_X = 48
CANVAS_INITIAL_OFFSET_Y = 0
CANVAS_INITIAL_SCALE = 1.0
