#
# Microlog. Copyright (c) 2023 laffra, dcharbon. All rights reserved.
#

import sys
import threading

from microlog import settings
from microlog import events
from microlog import stack
from microlog import threads

class Tracer(threads.BackgroundThread):
    """
    Tracer class that runs in a background thread and periodically generates stack traces.

    Parameters:
    - delay: The delay in seconds between generating stack traces.

    Functionality:
    - start(): Starts the background thread. Sets it as a daemon thread and initializes the stack trace and main thread ID.
    - getMainStackFrame(): Gets the stack frame for the main thread.
    - tick(): Runs every `delay` seconds. Merges the current stack trace with a new one generated from the main stack frame. 
    - getStack(): Generates a new stack trace with the given timestamp and starting frame. 
    - merge(): Synchronizes two stack traces by updating timestamps and caller information.
    - stop(): Generates a final stack trace with the current timestamp.
    """
    def start(self) -> None:
        self.setDaemon(True)
        self.stack = stack.Stack()
        self.mainThread = threading.currentThread().ident
        self.delay = settings.current.traceDelay
        return threads.BackgroundThread.start(self)

    def getMainStackFrame(self):
        """
        Gets the stack frame for the main thread.

        Parameters: 
        - self: The Tracer object.

        Functionality:
        - Iterates through the stack frames of all threads.
        - Returns the stack frame for the thread with ID matching self.mainThread.
        """
        for ident, frame in sys._current_frames().items():
            if ident == self.mainThread:
                return frame

    def tick(self) -> None:
        """
        tick(): Runs every `delay` seconds. Merges the current stack trace with a new one generated from the main stack frame.  

        Parameters:
        - self: The Tracer object.

        Functionality: 
        - Calls merge() to synchronize the current stack trace with a new one generated by getStack().

        """
        self.merge(self.getStack(events.now(), self.getMainStackFrame()))

    def getStack(self, when, frame):
        """
        getStack(): Generates a new stack trace with the given timestamp and starting frame.  

        Parameters:
        - when: The timestamp for the new stack trace. 
        - frame: The starting frame for the new stack trace.

        Functionality:
        - Returns a new Stack object representing a stack trace with the given timestamp and starting frame.
        """
        return stack.Stack(when, frame)

    def merge(self, stack: stack.Stack):
        """
        Synchronizes two stack traces by updating timestamps and caller information.  

        Parameters:
        - self: The Tracer object. 
        - stack: The new stack trace to merge with the current one.

        Functionality:
        - Iterates over the current stack trace and the new one call by call.
        - If two calls are the same, updates the timestamp of the new call to match the old one.
        - Otherwise, "marshalls" the old call by passing it the timestamp and caller of the new call.
        - Handles any remaining old calls by marshalling them with the last new call's timestamp and caller.
        - Finally, updates self.stack to the new stack.
        """
        caller = None
        for call1, call2 in zip(self.stack, stack):
            if call1 == call2:
                call2.when = call1.when
            else:
                call1.marshall(stack.when, caller)
            caller = call1
        if self.stack and len(self.stack) > len(stack):
            caller = self.stack[len(stack) - 1]
            for call in self.stack[len(stack):]:
                call.marshall(stack.when, caller)
                caller = call
        self.stack = stack

    def stop(self):
        """
        stop(): Generates a final stack trace with the current timestamp.  

        Parameters: 
        - self: The Tracer object.

        Functionality:
        - Calls merge() to synchronize the current stack trace with a new empty one with the current timestamp.
        """
        self.merge(stack.Stack(events.now()))

    
